### ISSUE TITLE
update to latest INTEGRITEE upstream

### ISSUE THREAD

**Issue by BillyWooo** [litentry/tee-worker#129]

**Comment by Kailai-Wang** [comment]
Have you checked how big the difference is? I'm not sure if we should wait for the new toolchain update (should be shipped together with v0.9.29 update)

**Comment by BillyWooo** [comment]
> Have you checked how big the difference is? I'm not sure if we should wait for the new toolchain update (should be shipped together with v0.9.29 update)

Overall architecture doesn't change much. But there are quite many files got touched. And the v0.9.29 + new toolchain are still on the way. Not sure when it will come. So I think we can give it a try.
