### ISSUE TITLE
Have one more TEE dev server

### ISSUE THREAD

**Issue by Kailai-Wang** [litentry/tee-worker#19]
As we have more engineers focusing on the TEE, it makes sense to have another TEE dev server to reduce the conflict chance.

**Comment by Kailai-Wang** [comment]
We are looking forward to setting up a new server with an existing one, if it doesn't work we'll go for the cloud providers.

**Comment by Kailai-Wang** [comment]
for reference: https://github.com/litentry/tee-worker/issues/74

**Comment by jingleizhang** [comment]
https://github.com/litentry/tee-worker/issues/74 is closed, so close this one as well.
