### ISSUE TITLE
signature algorithms of Evm and Substrate on TEE

### ISSUE THREAD

**Issue by jingleizhang** [litentry/tee-worker#28]
@jingleizhang commented on [Thu Sep 01 2022](https://github.com/litentry/litentry-pallets/issues/116)

---

@Kailai-Wang commented on [Thu Sep 01 2022](https://github.com/litentry/litentry-pallets/issues/116#issuecomment-1234423227)

I think it goes to the wrong repo :(

This pallet is deprecated. It should either go to the parachain repo or tee-worker repo

---

@Kailai-Wang commented on [Thu Sep 01 2022](https://github.com/litentry/litentry-pallets/issues/116#issuecomment-1234423419)

I should have archived this repo

**Comment by jingleizhang** [comment]
use case: Alice uses `Polkadot addressA` to send an extrinsic of identity linking, in which it says `Polkadot addressA` is linking with `Ethereum addressB`. With JWT issued by ID-hub when Alice logs in as `addressA`, TEE should verify the signed message for `addressB` is valid.

**Comment by Kailai-Wang** [comment]
I believe this is resolved, see the verification logic in IMP mock.

Superseded by #89 too
