### ISSUE TITLE
Create generate_VC functionality

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/tee-worker#37]
Create Generate VC Template functionality within TEE (See Identity Quest section below for more information) 

**generate_VC** should accept the following params:
- ruleset-id
- idhub-address
- params (Optional JSON payload)

**Comment by Kailai-Wang** [comment]
If it refers to the VC-generation extrinsic, it's already done in the vc-management pallet.
If it means the generation of the JSON-format VC with concrete fields, it's superseded by litentry/litentry-parachain#1022 (which is assigned to @jingleizhang as he designs the VC content)

Close this ticket for now.
