### ISSUE TITLE
Prepare the new instance located in Hangzhou office

### ISSUE THREAD

**Issue by jingleizhang** [litentry/tee-worker#74]
1. Install ubuntu20, intel SGX drivers, rust, and other required tools/drivers
2. Make sure it can build and run Parachain & Tee-work projects
3. Setup public ip address, allow remote ssh
4. Create new users for team members

Dell PowerEdge T40, Intel E2276 CPU(12 cores), 32G Mem, 250G Disk

![WX20220921-113448@2x](https://user-images.githubusercontent.com/7367842/191408620-22177b20-c2f0-4c11-aa60-a2dc6ad2bd8b.png)

**Comment by Marky-Shi** [comment]
Hi Eric, I just called the dell technician and they said this machine does not support ubuntu 20.04 system, do you want to reinstall ubuntu 18.04 system? Or are there other arrangements?

**Comment by jingleizhang** [comment]
Got it. Let's keep the version to 18.04.

**Comment by Marky-Shi** [comment]
<img width="582" alt="image" src="https://user-images.githubusercontent.com/87012234/191460261-984c16ab-6ada-4e0b-844c-52f9c11df389.png">

**Comment by Kailai-Wang** [comment]
Any news on this one? :)

**Comment by Marky-Shi** [comment]
I have successfully upgraded the system to 20.04 and am now working on setting up the TEE environment

**Comment by jingleizhang** [comment]
Let's close this Issue.
