### ISSUE TITLE
Create unit tests for async request functionality

### ISSUE THREAD

**Issue by StamfordDigital** [litentry/tee-worker#82]
We need to create some unit tests to ensure the async request functionality is working correctly.

**Suggestions:**
- [ ] Simulate multiple requests at the same time (e.g. 500 requests) and check to see how the async functionality responds
- [ ] Simulate a 3rd party service timeout within the TEE worker

**Comment by jingleizhang** [comment]
move it to issue litentry/litentry-parachain#1013
