### ISSUE TITLE
refactor https_daemon and verify_daemon

### ISSUE THREAD

**Issue by BillyWooo** [litentry/tee-worker#87]
As developing in parallel, both daemons grow and have some overlap. After discussion within the team, we decide to refactor them. 
New arch will collector all TrustedCall commands at stf level. Then push them to a new daemon (including twitter/discord verification, assertion verification, generate VC, etc.). The new daemon will distribute the tasks.

related to: #77 #38 #39 #82

**Comment by Kailai-Wang** [comment]
Is it covered by #96 ?

**Comment by BillyWooo** [comment]
> Is it covered by #96 ?

yes. Just updated the comment in #96
